"""Add price meal

Revision ID: 08693b63ee1e
Revises: 15431dce9a12
Create Date: 2025-02-20 22:07:42.557245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08693b63ee1e'
down_revision = '15431dce9a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('total')
        batch_op.drop_column('price')
        batch_op.drop_column('meal')

    # ### end Alembic commands ###
