"""dropped duplicate migration

Revision ID: 1922d52196d7
Revises: 97e3ebbaa2cb
Create Date: 2025-02-23 12:25:47.447143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1922d52196d7'
down_revision = '97e3ebbaa2cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_orders_client_id_client')),
    sa.ForeignKeyConstraint(['meal_id'], ['menu.id'], name=op.f('fk_orders_meal_id_menu')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_orders_restaurant_id_restaurants')),
    sa.PrimaryKeyConstraint('client_id', 'restaurant_id', 'meal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
