"""added colum to menu

Revision ID: 5de9d59f9aba
Revises: aaebd783a33c
Create Date: 2025-02-21 08:08:35.004925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de9d59f9aba'
down_revision = 'aaebd783a33c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_menu_restaurant_id_restaurants'), 'restaurants', ['restaurant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_menu_restaurant_id_restaurants'), type_='foreignkey')
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###
