"""deployment migration

Revision ID: 83ded1978d1f
Revises: 
Create Date: 2025-02-22 15:35:17.500853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ded1978d1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_constraint('fk_restaurants_menu_id_menu', type_='foreignkey')
        batch_op.drop_column('menu_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_restaurants_menu_id_menu', 'menu', ['menu_id'], ['id'])

    # ### end Alembic commands ###
