"""Added meal_id to Order

Revision ID: e05a9c10efa2
Revises: 08693b63ee1e
Create Date: 2025-02-21 08:46:48.474665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05a9c10efa2'
down_revision = '08693b63ee1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_orders_meal_id_menu'), 'menu', ['meal_id'], ['id'])
        batch_op.drop_column('meal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_orders_meal_id_menu'), type_='foreignkey')
        batch_op.drop_column('meal_id')

    # ### end Alembic commands ###
