"""updated table

Revision ID: f01e6c2a846d
Revises: 1922d52196d7
Create Date: 2025-02-27 20:33:45.375027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01e6c2a846d'
down_revision = '1922d52196d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('admin', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('restaurant_table_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_reservation_client_id_client')),
    sa.ForeignKeyConstraint(['restaurant_table_id'], ['restaurant_tables.id'], name=op.f('fk_reservation_restaurant_table_id_restaurant_tables')),
    sa.PrimaryKeyConstraint('restaurant_table_id', 'client_id')
    )
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_table_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.drop_constraint('fk_orders_client_id_client', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_orders_restaurant_table_id_reservation'), 'reservation', ['restaurant_table_id'], ['restaurant_table_id'])
        batch_op.create_foreign_key(batch_op.f('fk_orders_client_id_reservation'), 'reservation', ['client_id'], ['client_id'])
        batch_op.drop_column('table_number')

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_orders_client_id_reservation'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_orders_restaurant_table_id_reservation'), type_='foreignkey')
        batch_op.create_foreign_key('fk_orders_client_id_client', 'client', ['client_id'], ['id'])
        batch_op.drop_column('timestamp')
        batch_op.drop_column('restaurant_table_id')

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.drop_table('reservation')
    op.drop_table('restaurant_tables')
    # ### end Alembic commands ###
